apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: performance
spec:
  additionalKernelArgs:
  - nmi_watchdog=0
  - audit=0
  - mce=off
  - processor.max_cstate=1
  - idle=poll
  - intel_idle.max_cstate=0
  - nosmt
  - tsc=reliable
  cpu:
    isolated: "1,3-51"
    reserved: "0,2"
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 16 
      size: 1G
      node: 0
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  numa:
    topologyPolicy: "restricted"
  realTimeKernel:
    enabled: true
