apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: performance
spec:
  additionalKernelArgs:
  - nosmt
  cpu:
    isolated: "1,3-51"
    reserved: "0,2"
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 16 
      size: 1G
      node: 0
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  numa:
    topologyPolicy: "restricted"
  realTimeKernel:
    enabled: true
