apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - 'github.com/vitus133/ran-profiles/du/sriov?ref=dev'
  
resources:
  - sriov-network-node-policy-netdevice-mh.yaml
  - sriov-network-node-policy-netdevice-fh.yaml
