apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
# This profile is for typical lab DELL R640 with 2 x 26 pcores
  name: perf-r640-52
spec:
  additionalKernelArgs:
  - nosmt
  cpu:
    isolated: "1,3-51"
    reserved: "0,2"
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 16
      size: 1G
      node: 0
  nodeSelector:
    # Pay attention to the node label, create MCP accordingly
    node-role.kubernetes.io/worker-du-xl: ""
  numa:
    topologyPolicy: "restricted"
  realTimeKernel:
    enabled: true
